### ISSUE TITLE
Cadastro materiais Elotech

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/almoxarifado#3]
Verificar todas as tabelas necessárias para buscar materiais da Elotech. Criar serviços no projeto mscmcldap.

**Comment by aleodoni** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Levantamento Cadastro Materiais Elotech](https://trello.com/c/tRPs4eTJ/2-levantamento-cadastro-materiais-elotech)

**Comment by aleodoni** [comment]
Fábio está mapeando as tabelas no BD elotech

**Comment by aleodoni** [comment]
Conforme conversa com Aline, poderíamos utilizar os campos "ativoinativoai" e "itemanalisesn"

**Comment by fderosso** [comment]
Alterada a view para trazer o campo itemanalisesn.

**Comment by aleodoni** [comment]
Ja implementado na aplicação de serviços. Vou fechar essa issue. Se precisar criamos outras mais específicas.
